author: Valentin Knabel
author_url: https://twitter.com/vknabel
github_url: https://github.com/vknabel/EasyInject
module: EasyInject
module_version: 0.8.0
root_url: https://vknabel.github.io/EasyInject/
readme: README.md
output: docs/
theme: fullwidth
