language: generic
sudo: required
dist: trusty
matrix:
  include:
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode7.3
      language: objective-c
      xcode_project: EasyInject.xcodeproj
      xcode_scheme: EasyInjectTests
      env: SWIFT_VERSION=2.2
    - os: linux
      env: SWIFT_VERSION=3.0-PREVIEW-6
install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
script:
  - swift build
  - swift test
